# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f97e9aacb018274dc56b4c3bd10c3db8aab9d6965b5cb7ff16acb3bf78625c546af725d24d04691ec81f28830a6be7612fe9b376641afcf785542b7bc41604

test:
  secret_key_base: da273dd47b7f9564ed26914bb976f34f0da8ac213c95f6055a9c7c44c9643954bc395caaa3fe12e51003850b3cca5e1cdc4c0a7688dd87beb8d448c815f24125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
